# Generated by Django 4.2.7 on 2023-11-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0002_local_local_rua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='local_cep',
            field=models.CharField(default='Inserir', max_length=8),
        ),
    ]
