# Generated by Django 4.2.6 on 2024-01-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0002_usuario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
