# Generated by Django 4.2.7 on 2023-11-07 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0002_usuario_usuario_email_usuario_usuario_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='evento_datahora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='evento',
            name='evento_valor',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='local',
            name='local_estacionamento',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='local',
            name='local_latitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='local',
            name='local_longitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='local',
            name='local_cep',
            field=models.CharField(default='Inserir', max_length=8),
        ),
        migrations.AlterField(
            model_name='local',
            name='local_rua',
            field=models.CharField(default='Inserir', max_length=200),
        ),
    ]
