# Generated by Django 4.2.7 on 2023-11-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0003_alter_local_local_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='local_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='local',
            name='local_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
