# Generated by Django 4.2.7 on 2023-11-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0003_evento_evento_datahora_evento_evento_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='evento_valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
