# Generated by Django 4.2.7 on 2023-11-07 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0004_alter_evento_evento_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='evento_local',
            field=models.ForeignKey(default='inserir', on_delete=django.db.models.deletion.CASCADE, to='vumbora.local'),
        ),
    ]
