# Generated by Django 4.2.5 on 2023-11-07 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0004_alter_local_local_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='evento_local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vumbora.local'),
        ),
    ]
