# Generated by Django 4.2.7 on 2023-11-07 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0005_evento_evento_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='evento_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vumbora.local'),
        ),
    ]
