# Generated by Django 4.2.7 on 2023-11-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0005_evento_evento_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local',
            name='local_cep',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='local',
            name='local_nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='local',
            name='local_rua',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_nome',
            field=models.CharField(max_length=200),
        ),
    ]
