# Generated by Django 4.2.7 on 2023-11-12 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0007_rename_local_nome_local_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='evento_datahora',
            new_name='datahora',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='evento_genero',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='evento_local',
            new_name='local',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='evento_nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='evento_valor',
            new_name='valor',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='local_bairro',
            new_name='bairro',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='local_cep',
            new_name='cep',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='local_estacionamento',
            new_name='estacionamento',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='local_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='local_longitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='local_rua',
            new_name='rua',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario_tipo',
            new_name='tipo',
        ),
    ]
