# Generated by Django 4.2.7 on 2023-11-07 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0007_alter_evento_evento_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='evento_local',
        ),
    ]
