# Generated by Django 4.2.7 on 2023-11-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0008_rename_evento_datahora_evento_datahora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='info',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
