# Generated by Django 4.2.7 on 2023-11-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0010_rename_info_evento_descricao_remove_local_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='identificacao',
            field=models.CharField(max_length=14),
        ),
    ]
