# Generated by Django 4.2.7 on 2023-11-14 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0011_alter_usuario_identificacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='identificacao',
            new_name='identidade',
        ),
    ]
