# Generated by Django 4.2.7 on 2023-11-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0012_rename_identificacao_usuario_identidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='numero',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
