# Generated by Django 4.2.7 on 2023-11-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0013_local_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='arte',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='genero',
            field=models.CharField(choices=[('E', 'Exposição'), ('F', 'Festa'), ('G', 'Gastronomia'), ('S', 'Show'), ('T', 'Teatro')], max_length=1),
        ),
    ]
