# Generated by Django 4.2.7 on 2023-11-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0014_evento_arte_alter_evento_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
