# Generated by Django 4.2.7 on 2023-12-07 23:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0015_usuario_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('zona', models.CharField(choices=[('ZN', 'Zona Norte'), ('ZS', 'Zona Sul'), ('ZL', 'Zona Leste'), ('ZO', 'Zona Oeste')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Comenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=200)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('E', 'Exposição'), ('F', 'Festa'), ('G', 'Gastronomia'), ('S', 'Show'), ('T', 'Teatro')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='evento',
            name='genero',
        ),
        migrations.AddField(
            model_name='evento',
            name='genero',
            field=models.ManyToManyField(to='vumbora.genero'),
        ),
        migrations.AlterField(
            model_name='local',
            name='bairro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vumbora.bairro'),
        ),
    ]
