# Generated by Django 4.2.7 on 2023-12-07 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0016_bairro_comenta_genero_remove_evento_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comenta',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vumbora.evento'),
        ),
        migrations.AddField(
            model_name='comenta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vumbora.usuario'),
        ),
    ]
