# Generated by Django 4.2.4 on 2023-12-13 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0016_bairro_genero_alter_local_options_alter_evento_arte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vumbora.usuario'),
        ),
    ]
