# Generated by Django 4.2.7 on 2023-11-27 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0017_alter_avaliacao_nota_alter_avaliacao_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='usuario',
        ),
    ]
