# Generated by Django 4.2.7 on 2023-12-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0018_alter_evento_arte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
