# Generated by Django 4.2.7 on 2023-11-27 00:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0018_remove_avaliacao_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('comentario', models.CharField(max_length=200, null=True)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vumbora.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vumbora.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
    ]
