# Generated by Django 4.2.7 on 2023-12-08 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0019_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='local',
            options={'verbose_name_plural': 'Locais'},
        ),
    ]
