# Generated by Django 4.2.7 on 2023-11-27 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0019_avaliacoa_delete_avaliacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avaliacoa',
            new_name='Avaliacao',
        ),
    ]
