# Generated by Django 4.2.7 on 2023-12-08 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0020_alter_local_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comenta',
            options={'verbose_name_plural': 'Comentários'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'verbose_name_plural': 'Gêneros'},
        ),
    ]
