# Generated by Django 4.2.7 on 2023-11-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0022_evento_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='evento',
        ),
        migrations.AddField(
            model_name='evento',
            name='avaliacao',
            field=models.ManyToManyField(to='vumbora.avaliacao'),
        ),
    ]
