# Generated by Django 4.2.4 on 2023-12-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0017_evento_usuario'),
        ('vumbora', '0023_evento_usuario'),
    ]

    operations = [
    ]
