# Generated by Django 4.2.7 on 2023-11-28 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0023_remove_avaliacao_evento_evento_avaliacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='avaliacao',
            new_name='avalia',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vumbora.evento'),
        ),
    ]
