# Generated by Django 4.2.7 on 2023-11-28 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0024_rename_avaliacao_evento_avalia_avaliacao_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='event',
            new_name='evento',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='avalia',
        ),
    ]
