# Generated by Django 4.2.7 on 2023-12-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0025_rename_event_avaliacao_evento_remove_evento_avalia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='comentario',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
