# Generated by Django 4.2.5 on 2023-12-11 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vumbora', '0026_alter_avaliacao_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='local',
            options={'verbose_name_plural': 'Locais'},
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
